# Generated by Django 3.2.9 on 2021-12-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(),
        ),
    ]
